version: '2'

services:

  postgres:
    image: circleci/postgres:9.5-alpine
    environment:
      - POSTGRES_DB=testDatabase
      - POSTGRES_USER=circleci
      - POSTGRES_PASSWORD=defaultPassword
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
  postgres:
    driver: bridge
